name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  centos8:
    runs-on: ubuntu-latest

    container: centos:8

    steps:
      - run: |
          sed -i 's|#baseurl=|baseurl=|g'       /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|mirror|vault|g'             /etc/yum.repos.d/CentOS-*.repo
          sed -i 's|http:|https:|g'             /etc/yum.repos.d/CentOS-*.repo

          dnf -y update
          dnf -y install curl xz gcc-c++

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm

      - run:  /opt/ppkg/installed/uppm/bin/uppm --help
      - run:  /opt/ppkg/installed/uppm/bin/uppm --version
      - run:  /opt/ppkg/installed/uppm/bin/uppm env
      - run:  |
          export SSL_CERT_FILE=/opt/ppkg/core/etc/ssl/certs/cacert.pem
          /opt/ppkg/installed/uppm/bin/uppm update
      - run:  /opt/ppkg/installed/uppm/bin/uppm search    zip
      - run:  /opt/ppkg/installed/uppm/bin/uppm info      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm install   unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm tree      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm uninstall unzip


  centos7:
    runs-on: ubuntu-latest

    container: centos:7

    steps:
      - run:  yum -y update
      - run:  yum -y install curl xz gcc-c++

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm

      - run:  /opt/ppkg/installed/uppm/bin/uppm --help
      - run:  /opt/ppkg/installed/uppm/bin/uppm --version
      - run:  /opt/ppkg/installed/uppm/bin/uppm env
      - run:  |
          export SSL_CERT_FILE=/opt/ppkg/core/etc/ssl/certs/cacert.pem
          /opt/ppkg/installed/uppm/bin/uppm update
      - run:  /opt/ppkg/installed/uppm/bin/uppm search    zip
      - run:  /opt/ppkg/installed/uppm/bin/uppm info      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm install   unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm tree      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm uninstall unzip

  centos_6_10:
    if: ${{ false }}

    runs-on: ubuntu-latest

    container: centos:6.10

    steps:
      - run: |
          sed -i 's|#baseurl=|baseurl=|g'       /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|mirror|vault|g'             /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's|http:|https:|g'             /etc/yum.repos.d/CentOS-Base.repo

          yum -y update
          yum -y install curl xz gcc-c++

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm

      - run:  /opt/ppkg/installed/uppm/bin/uppm --help
      - run:  /opt/ppkg/installed/uppm/bin/uppm --version
      - run:  /opt/ppkg/installed/uppm/bin/uppm env
      - run:  |
          export SSL_CERT_FILE=/opt/ppkg/core/etc/ssl/certs/cacert.pem
          /opt/ppkg/installed/uppm/bin/uppm update
      - run:  /opt/ppkg/installed/uppm/bin/uppm search    zip
      - run:  /opt/ppkg/installed/uppm/bin/uppm info      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm install   unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm tree      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm uninstall unzip

