name: Debian GNU/Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['8.11', '9.13', '10.7', '11.5']

    container: debian:${{ matrix.tag }}

    steps:
      - run:  id
      - run:  apt -y update
      - run:  apt -y install curl g++ xz-utils

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm

      - run:  /opt/ppkg/installed/uppm/bin/uppm --help
      - run:  /opt/ppkg/installed/uppm/bin/uppm --version
      - run:  /opt/ppkg/installed/uppm/bin/uppm env
      - run:  /opt/ppkg/installed/uppm/bin/uppm update
      - run:  /opt/ppkg/installed/uppm/bin/uppm search    zip
      - run:  /opt/ppkg/installed/uppm/bin/uppm info      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm install   unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm tree      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm uninstall unzip
