name: gentoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gentoo:
    runs-on: ubuntu-latest

    container: madhacking/gentoo

    steps:
      - run:  emerge cmake dev-util/ninja gcc pkg-config dev-vcs/git net-misc/curl dev-libs/libgit2 libarchive dev-libs/libyaml dev-libs/jansson dev-db/sqlite

      - uses: actions/checkout@v3

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version
      - run:  ./output/bin/uppm env
      - run:  ./output/bin/uppm update
      - run:  ./output/bin/uppm search    zip
      - run:  ./output/bin/uppm info      unzip
      - run:  ./output/bin/uppm fetch     unzip
      - run:  ./output/bin/uppm install   unzip
      - run:  ./output/bin/uppm tree      unzip
      - run:  ./output/bin/uppm uninstall unzip
