name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run:  brew update
      - run:  brew install cmake ninja tree curl libyaml libgit2 libarchive

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_FIND_ROOT_PATH="$(brew --prefix openssl@1.1);$(brew --prefix libarchive)"
      - run:  cmake --build   build.d
      - run:  cmake --install build.d

      - run:  tree output

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version
      - run:  ./output/bin/uppm env
      - run:  ./output/bin/uppm update
      - run:  ./output/bin/uppm search    zip
      - run:  ./output/bin/uppm info      unzip
      - run:  ./output/bin/uppm install   unzip
      - run:  ./output/bin/uppm tree      unzip
      - run:  ./output/bin/uppm uninstall unzip
