name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run:  brew update
      - run:  brew install cmake ninja tree

      - run:  echo "VCPKG_ROOT=$HOME/.vcpkg/root" >> "$GITHUB_ENV"
      - run:  install -d $VCPKG_ROOT
      - run:  git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT

      - run:  vcpkg install curl openssl libyaml libgit2 libarchive

      - run:  cmake --version
      - run:  cmake -S . -B   build.d -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d
      - run:  tree output
      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version
