name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12
    
    strategy:
      fail-fast: false
      matrix:
        version: [9]

    steps:
      - uses: actions/checkout@v3

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          run: |
            run sudo pkgin -y install cmake ninja-build pkg-config clang curl libgit2 libarchive libyaml jansson sqlite

            run cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
            run cmake --build   build.d
            run cmake --install build.d

            export LD_LIBRARY_PATH=/usr/pkg/lib

            run ./output/bin/uppm --help
            run ./output/bin/uppm --version
            run ./output/bin/uppm env

            run sudo rm -rf /usr/pkg/etc/openssl
            run sudo pkgin -y install mozilla-rootcerts
            run sudo mozilla-rootcerts install

            if [ ${{matrix.version}} -eq 8 ] ; then
                export SSL_CERT_FILE=/usr/pkg/etc/openssl/certs/ca-certificates.crt
            else
                export SSL_CERT_FILE=/etc/openssl/certs/ca-certificates.crt
            fi

            run ./output/bin/uppm update
            run ./output/bin/uppm search    zip
            run ./output/bin/uppm info      unzip
            run ./output/bin/uppm fetch     unzip
            run ./output/bin/uppm install   unzip
            run ./output/bin/uppm tree      unzip
            run ./output/bin/uppm uninstall unzip
