name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/openbsd6
          run: |
            run sudo pkg_add cmake ninja gcc-11.2.0p0 tree curl openssl-1.1.1n libgit2 libarchive libyaml jansson

            run cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_VERBOSE_MAKEFILE=ON
            run cmake --build   build.d
            run cmake --install build.d

            run tree output

            run ./output/bin/uppm --help
            run ./output/bin/uppm --version
            run ./output/bin/uppm env
            run ./output/bin/uppm update
            run ./output/bin/uppm search    zip
            run ./output/bin/uppm info      unzip
            run ./output/bin/uppm install   unzip
            run ./output/bin/uppm tree      unzip
            run ./output/bin/uppm uninstall unzip
