name: ppkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ppkg:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm

      - run:  /opt/ppkg/installed/uppm/bin/uppm --help
      - run:  /opt/ppkg/installed/uppm/bin/uppm --version
      - run:  /opt/ppkg/installed/uppm/bin/uppm env

      - run:  SSL_CERT_FILE=/opt/ppkg/core/etc/ssl/certs/cacert.pem /opt/ppkg/installed/uppm/bin/uppm update

      - run:  /opt/ppkg/installed/uppm/bin/uppm search    zip
      - run:  /opt/ppkg/installed/uppm/bin/uppm info      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm install   unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm tree      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm uninstall unzip
