name: Rocky Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['8', '8.5']

    container: rockylinux:${{ matrix.tag }}

    steps:
      - run:  dnf -y update
      - run:  dnf -y install curl gcc

      - uses: actions/checkout@main

      - name: install ppkg
        run: |
          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
          chmod a+x ppkg
          ./ppkg setup

      - run:  ./ppkg update
      - run:  ./ppkg install uppm
      - run:  ./ppkg tree    uppm

      - run:  /opt/ppkg/installed/uppm/bin/uppm --help
      - run:  /opt/ppkg/installed/uppm/bin/uppm --version
      - run:  /opt/ppkg/installed/uppm/bin/uppm env
      - run:  /opt/ppkg/installed/uppm/bin/uppm update
      - run:  /opt/ppkg/installed/uppm/bin/uppm search    zip
      - run:  /opt/ppkg/installed/uppm/bin/uppm info      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm install   unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm tree      unzip
      - run:  /opt/ppkg/installed/uppm/bin/uppm uninstall unzip
