name: vcpkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vcpkg:

    runs-on: ubuntu-latest

    steps:
      - run:  sudo apt -y update
      - run:  sudo apt -y install cmake ninja-build pkg-config linux-headers-generic

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libgit2 libarchive libyaml jansson sqlite3

      - run:  cmake -S . -B   build.d -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version
      - run:  ./output/bin/uppm env
      - run:  ./output/bin/uppm update
      - run:  ./output/bin/uppm search    zip
      - run:  ./output/bin/uppm info      unzip
      - run:  ./output/bin/uppm install   unzip
      - run:  ./output/bin/uppm tree      unzip
      - run:  ./output/bin/uppm uninstall unzip
