name: voidlinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  voidlinux:
    strategy:
      fail-fast: false
      matrix:
        variant: ['voidlinux', 'voidlinux-musl']

    runs-on: ubuntu-latest

    container: voidlinux/${{ matrix.variant }}

    steps:
      - run: xbps-install -Suy xbps
      - run: xbps-install -Suy cmake ninja gcc pkg-config libcurl-devel libgit2-devel libarchive-devel libyaml-devel jansson-devel

      # https://github.com/actions/checkout/issues/334
      - uses: actions/checkout@v1

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version
      - run:  ./output/bin/uppm env
      - run:  ./output/bin/uppm update
      - run:  ./output/bin/uppm search    zip
      - run:  ./output/bin/uppm info      unzip
      - run:  ./output/bin/uppm install   unzip
      - run:  ./output/bin/uppm tree      unzip
      - run:  ./output/bin/uppm uninstall unzip
